export const explicitMemBenchmark = {
  benchmark: "LongMemEval-S",
  generated: "1 August 2026",
  questions: 500,
  passedQuestions: 499,
  answerAccuracy: "99.8%",
  answerFaithfulness: "100%",
  answerEvidenceHitRate: "78.2%",
  retrievalRecallAtK: "100%",
  retrievalReceiptCoverage: "100%",
} as const;

export const explicitMemQuestionTypes = [
  { label: "Knowledge update", count: 78, accuracy: "100%", passed: "78 / 78" },
  { label: "Multi-session", count: 133, accuracy: "100%", passed: "133 / 133" },
  { label: "Single-session assistant", count: 56, accuracy: "100%", passed: "56 / 56" },
  { label: "Single-session preference", count: 30, accuracy: "100%", passed: "30 / 30" },
  { label: "Single-session user", count: 70, accuracy: "100%", passed: "70 / 70" },
  { label: "Temporal reasoning", count: 133, accuracy: "99.2%", passed: "132 / 133" },
] as const;

export const explicitMemStudies = [
  {
    id: "longmemeval-s",
    evidenceClass: "External-dataset benchmark",
    dataset: "LongMemEval-S",
    generated: explicitMemBenchmark.generated,
    scope: "Fixed answer synthesis",
    metricLabel: "Answer accuracy",
    metricValue: "99.8%",
    sample: "499 / 500 answers correct",
    method: "The complete 500-question set was scored with deterministic normalized answer matching under a fixed evaluation profile.",
    failure: "One temporal item differed from the upstream gold answer, so the strict perfect-score gate remained unmet.",
    limitation: "Benchmark-scoped result. It is not an LLM-judged score, a cross-dataset synthesis result, or a hosted latency claim.",
    evidenceStatus: "Versioned result and failure records retained for controlled review.",
  },
  {
    id: "locomo",
    evidenceClass: "External-dataset benchmark",
    dataset: "LoCoMo",
    generated: "3 June 2026",
    scope: "Retrieval evaluation",
    metricLabel: "Expected-memory recall",
    metricValue: "93.52%",
    sample: "1,986 runtime cases",
    method: "A fixed retrieval profile was evaluated against 1,986 cases using expected-memory recall as the primary metric.",
    failure: "Secondary recall measures were lower than the primary measure and remain outside this headline claim.",
    limitation: "LoCoMo-specific retrieval and context recall. It does not measure generated-answer accuracy and is not the default generic runtime.",
    evidenceStatus: "Versioned result and failure records retained for controlled review.",
  },
  {
    id: "cross-dataset",
    evidenceClass: "First-party evaluation on external datasets",
    dataset: "BEAM, ConvoMem, LoCoMo, LongMemEval",
    generated: "3 June 2026",
    scope: "Cross-dataset candidate generation",
    metricLabel: "Held-out recall@400",
    metricValue: "98.93%",
    sample: "740 held-out source cases",
    method: "A fixed candidate-generation profile was evaluated on held-out cases drawn from five external datasets.",
    failure: "Smaller candidate pools performed below the published recall@400 result.",
    limitation: "High-recall candidate generation for downstream ranking. It is not final top-50 ranking quality or answer accuracy.",
    evidenceStatus: "Versioned result and split records retained for controlled review.",
  },
  {
    id: "generic-answer",
    evidenceClass: "First-party evaluation",
    dataset: "Generic and non-LongMemEval fixtures",
    generated: "6 June 2026",
    scope: "Generic answer support",
    metricLabel: "Deterministic accuracy",
    metricValue: "100%",
    sample: "256 / 256 cases passed",
    method: "A fixed set of local, external, production-shaped, unseen-generic, and generated cases was scored with deterministic support checks.",
    failure: "No scored failure appears in this artifact. That limits failure analysis and increases the importance of broader adversarial and provider-judged evaluation.",
    limitation: "Deterministic extractive answer support. It is not LLM-judged provider scoring or proof of open-ended answer quality.",
    evidenceStatus: "Versioned result records retained for controlled review.",
  },
] as const;
